version: 2.0
jobs:
  build:
    docker:
      - image: membrane/bionic-membrane:latest
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix test
      - run:
          command: mix test --only long_running
          no_output_timeout: 15m
